apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
      env:
      - name: USER_NAME
        valueFrom:
            secretKeyRef:
              name: mongo-secret
              value: mongo-user
      - name: USER_PWD
        valueFrom:
            secretKeyRef:
              name: mongo-secret
              value: mongo-password
      - name: DB_URL
        valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url


---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app.kubernetes.io/name: webapp-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017